spring:
  datasource:
    host: bj-cynosdbmysql-grp-5dvrc4s6.sql.tencentcdb.com
    port: 28168
    name: bpmn_flowable
    username: root
    password: Asd@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
flowable:
  # 关闭定时任务JOB
  async-executor-activate: false
  # 将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时,会自动将数据库表结构升级至新版本。
  database-schema-update: true
  common:
    app:
      idm-url: http://127.0.0.1://80/flowable-idm

logging:
  level:
    org.flowable: DEBUG
